Algoritmo "Exercicio Medidas"
Var
a, b,c : real
Quadrado, Triangulo, Trapezio: real


Inicio
escreva("Digite a medida A: ")
leia(a)

escreva("Digite a medida B: ")
leia(b)

escreva("Digite a medida C: ")
leia(c)

Quadrado <- a * 4 // a * a
escreval("AREA QUADRADO = ",Quadrado:8:4)

Triangulo <- b * 2 // a * b /2
escreval("Area Triangulo = ", Triangulo:8:4)

Trapezio <- (a + b) * c / 2
escreval("Area Trapezio = ", trapezio:8:4)



Fimalgoritmo