Algoritmo "Media Idades"
Var
nome1, nome2: caractere
idade1, idade2: inteiro
mediaIdade: real

Inicio
escreval("Dados da primeira pessoa: ")

escreval("Nome: ")
leia(nome1)

escreva("Idade: ")
leia(idade1)

escreval("Dados da segunda pessoa: ")

escreval("Nome: ")
leia(nome2)

escreva("Idade: ")
leia(idade2)

MediaIdade <- (idade1 + idade2) /2
escreval("A idade media de ", nome1, " e ", nome2, " eh de ", MediaIdade:4:1, " anos")



Fimalgoritmo